// flow-typed signature: 4b0849c5cdb599b98c34beaa2f8384de
// flow-typed version: <<STUB>>/babel-preset-es2016_v^6.22.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2016'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2016' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-es2016/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-es2016/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-es2016/lib/index'>;
}
