// flow-typed signature: 52ec7d952e23091ff45f80adada48ac0
// flow-typed version: <<STUB>>/bcoin_v^1.0.0-beta.12/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bcoin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bcoin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bcoin/browser/empty' {
  declare module.exports: any;
}

declare module 'bcoin/browser/index' {
  declare module.exports: any;
}

declare module 'bcoin/browser/server' {
  declare module.exports: any;
}

declare module 'bcoin/browser/transform' {
  declare module.exports: any;
}

declare module 'bcoin/browser/wsproxy' {
  declare module.exports: any;
}

declare module 'bcoin/examples/chain' {
  declare module.exports: any;
}

declare module 'bcoin/examples/client' {
  declare module.exports: any;
}

declare module 'bcoin/examples/miner' {
  declare module.exports: any;
}

declare module 'bcoin/examples/node' {
  declare module.exports: any;
}

declare module 'bcoin/examples/peer' {
  declare module.exports: any;
}

declare module 'bcoin/examples/plugin' {
  declare module.exports: any;
}

declare module 'bcoin/examples/tx' {
  declare module.exports: any;
}

declare module 'bcoin/examples/wallet' {
  declare module.exports: any;
}

declare module 'bcoin/lib/bcoin' {
  declare module.exports: any;
}

declare module 'bcoin/lib/bip70/certs' {
  declare module.exports: any;
}

declare module 'bcoin/lib/bip70/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/bip70/payment' {
  declare module.exports: any;
}

declare module 'bcoin/lib/bip70/paymentack' {
  declare module.exports: any;
}

declare module 'bcoin/lib/bip70/paymentdetails' {
  declare module.exports: any;
}

declare module 'bcoin/lib/bip70/paymentrequest' {
  declare module.exports: any;
}

declare module 'bcoin/lib/bip70/pk' {
  declare module.exports: any;
}

declare module 'bcoin/lib/bip70/x509' {
  declare module.exports: any;
}

declare module 'bcoin/lib/blockchain/chain' {
  declare module.exports: any;
}

declare module 'bcoin/lib/blockchain/chaindb' {
  declare module.exports: any;
}

declare module 'bcoin/lib/blockchain/chainentry' {
  declare module.exports: any;
}

declare module 'bcoin/lib/blockchain/common' {
  declare module.exports: any;
}

declare module 'bcoin/lib/blockchain/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/blockchain/layout-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/blockchain/layout' {
  declare module.exports: any;
}

declare module 'bcoin/lib/btc/amount' {
  declare module.exports: any;
}

declare module 'bcoin/lib/btc/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/btc/uri' {
  declare module.exports: any;
}

declare module 'bcoin/lib/coins/coins' {
  declare module.exports: any;
}

declare module 'bcoin/lib/coins/coinview' {
  declare module.exports: any;
}

declare module 'bcoin/lib/coins/compress' {
  declare module.exports: any;
}

declare module 'bcoin/lib/coins/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/coins/undocoins' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/aes' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/backend-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/backend' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/chachapoly' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/crypto' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/ec-elliptic' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/ec-secp256k1' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/ec' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/pk-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/pk' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/schnorr' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/scrypt' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/sha256' {
  declare module.exports: any;
}

declare module 'bcoin/lib/crypto/siphash' {
  declare module.exports: any;
}

declare module 'bcoin/lib/db/backends-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/db/backends' {
  declare module.exports: any;
}

declare module 'bcoin/lib/db/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/db/ldb' {
  declare module.exports: any;
}

declare module 'bcoin/lib/db/level' {
  declare module.exports: any;
}

declare module 'bcoin/lib/db/lowlevelup' {
  declare module.exports: any;
}

declare module 'bcoin/lib/db/memdb' {
  declare module.exports: any;
}

declare module 'bcoin/lib/env' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/common' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/hd' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/mnemonic' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/private' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/public' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/wordlist-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/wordlist' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/words/chinese-simplified' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/words/chinese-traditional' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/words/english' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/words/french' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/words/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/words/italian' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/words/japanese' {
  declare module.exports: any;
}

declare module 'bcoin/lib/hd/words/spanish' {
  declare module.exports: any;
}

declare module 'bcoin/lib/http/base' {
  declare module.exports: any;
}

declare module 'bcoin/lib/http/client' {
  declare module.exports: any;
}

declare module 'bcoin/lib/http/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/http/request' {
  declare module.exports: any;
}

declare module 'bcoin/lib/http/rpc' {
  declare module.exports: any;
}

declare module 'bcoin/lib/http/rpcbase' {
  declare module.exports: any;
}

declare module 'bcoin/lib/http/rpcclient' {
  declare module.exports: any;
}

declare module 'bcoin/lib/http/server' {
  declare module.exports: any;
}

declare module 'bcoin/lib/http/wallet' {
  declare module.exports: any;
}

declare module 'bcoin/lib/mempool/fees' {
  declare module.exports: any;
}

declare module 'bcoin/lib/mempool/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/mempool/layout-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/mempool/layout' {
  declare module.exports: any;
}

declare module 'bcoin/lib/mempool/mempool' {
  declare module.exports: any;
}

declare module 'bcoin/lib/mempool/mempoolentry' {
  declare module.exports: any;
}

declare module 'bcoin/lib/mining/common' {
  declare module.exports: any;
}

declare module 'bcoin/lib/mining/cpuminer' {
  declare module.exports: any;
}

declare module 'bcoin/lib/mining/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/mining/mine' {
  declare module.exports: any;
}

declare module 'bcoin/lib/mining/miner' {
  declare module.exports: any;
}

declare module 'bcoin/lib/mining/template' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/bip150' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/bip151' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/bip152' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/common' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/dns-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/dns' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/framer' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/hostlist' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/packets' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/parser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/peer' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/pool' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/proxysocket' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/seeds/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/seeds/main' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/seeds/testnet' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/socks' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/tcp-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/tcp' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/upnp-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/net/upnp' {
  declare module.exports: any;
}

declare module 'bcoin/lib/node/config' {
  declare module.exports: any;
}

declare module 'bcoin/lib/node/fullnode' {
  declare module.exports: any;
}

declare module 'bcoin/lib/node/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/node/logger' {
  declare module.exports: any;
}

declare module 'bcoin/lib/node/node' {
  declare module.exports: any;
}

declare module 'bcoin/lib/node/nodeclient' {
  declare module.exports: any;
}

declare module 'bcoin/lib/node/spvnode' {
  declare module.exports: any;
}

declare module 'bcoin/lib/pkg' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/abstractblock' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/address' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/block' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/coin' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/headers' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/input' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/invitem' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/keyring' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/memblock' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/merkleblock' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/mtx' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/netaddress' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/outpoint' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/output' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/tx' {
  declare module.exports: any;
}

declare module 'bcoin/lib/primitives/txmeta' {
  declare module.exports: any;
}

declare module 'bcoin/lib/protocol/consensus' {
  declare module.exports: any;
}

declare module 'bcoin/lib/protocol/errors' {
  declare module.exports: any;
}

declare module 'bcoin/lib/protocol/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/protocol/network' {
  declare module.exports: any;
}

declare module 'bcoin/lib/protocol/networks' {
  declare module.exports: any;
}

declare module 'bcoin/lib/protocol/policy' {
  declare module.exports: any;
}

declare module 'bcoin/lib/protocol/timedata' {
  declare module.exports: any;
}

declare module 'bcoin/lib/script/common' {
  declare module.exports: any;
}

declare module 'bcoin/lib/script/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/script/opcode' {
  declare module.exports: any;
}

declare module 'bcoin/lib/script/program' {
  declare module.exports: any;
}

declare module 'bcoin/lib/script/script' {
  declare module.exports: any;
}

declare module 'bcoin/lib/script/scriptnum' {
  declare module.exports: any;
}

declare module 'bcoin/lib/script/sigcache' {
  declare module.exports: any;
}

declare module 'bcoin/lib/script/stack' {
  declare module.exports: any;
}

declare module 'bcoin/lib/script/witness' {
  declare module.exports: any;
}

declare module 'bcoin/lib/types' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/asn1' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/asyncemitter' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/asyncobject' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/base32' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/base58' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/bloom' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/co' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/encoding' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/fs' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/heap' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/ip' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/lazy-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/lazy' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/list' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/lock' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/lru' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/map' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/murmur3' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/native' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/nexttick-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/nexttick' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/nfkd-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/nfkd' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/pem' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/protobuf' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/rbt' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/reader' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/staticwriter' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/util' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/validator' {
  declare module.exports: any;
}

declare module 'bcoin/lib/utils/writer' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/account' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/client' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/common' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/http' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/layout-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/layout' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/masterkey' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/path' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/plugin' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/records' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/rpc' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/server' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/txdb' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/wallet' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/walletdb' {
  declare module.exports: any;
}

declare module 'bcoin/lib/wallet/walletkey' {
  declare module.exports: any;
}

declare module 'bcoin/lib/workers/framer' {
  declare module.exports: any;
}

declare module 'bcoin/lib/workers/index' {
  declare module.exports: any;
}

declare module 'bcoin/lib/workers/jobs' {
  declare module.exports: any;
}

declare module 'bcoin/lib/workers/master' {
  declare module.exports: any;
}

declare module 'bcoin/lib/workers/packets' {
  declare module.exports: any;
}

declare module 'bcoin/lib/workers/parser-client' {
  declare module.exports: any;
}

declare module 'bcoin/lib/workers/parser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/workers/worker-browser' {
  declare module.exports: any;
}

declare module 'bcoin/lib/workers/worker' {
  declare module.exports: any;
}

declare module 'bcoin/lib/workers/workerpool' {
  declare module.exports: any;
}

declare module 'bcoin/migrate/chaindb0to1' {
  declare module.exports: any;
}

declare module 'bcoin/migrate/chaindb1to2' {
  declare module.exports: any;
}

declare module 'bcoin/migrate/coins-old' {
  declare module.exports: any;
}

declare module 'bcoin/migrate/coinview-old' {
  declare module.exports: any;
}

declare module 'bcoin/migrate/compress-old' {
  declare module.exports: any;
}

declare module 'bcoin/migrate/ensure-tip-index' {
  declare module.exports: any;
}

declare module 'bcoin/migrate/walletdb2to3' {
  declare module.exports: any;
}

declare module 'bcoin/migrate/walletdb3to4' {
  declare module.exports: any;
}

declare module 'bcoin/migrate/walletdb4to5' {
  declare module.exports: any;
}

declare module 'bcoin/migrate/walletdb5to6' {
  declare module.exports: any;
}

declare module 'bcoin/scripts/dump' {
  declare module.exports: any;
}

declare module 'bcoin/scripts/fuzz' {
  declare module.exports: any;
}

declare module 'bcoin/scripts/gen' {
  declare module.exports: any;
}

declare module 'bcoin/vendor/setimmediate' {
  declare module.exports: any;
}

declare module 'bcoin/vendor/unorm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bcoin/browser/empty.js' {
  declare module.exports: $Exports<'bcoin/browser/empty'>;
}
declare module 'bcoin/browser/index.js' {
  declare module.exports: $Exports<'bcoin/browser/index'>;
}
declare module 'bcoin/browser/server.js' {
  declare module.exports: $Exports<'bcoin/browser/server'>;
}
declare module 'bcoin/browser/transform.js' {
  declare module.exports: $Exports<'bcoin/browser/transform'>;
}
declare module 'bcoin/browser/wsproxy.js' {
  declare module.exports: $Exports<'bcoin/browser/wsproxy'>;
}
declare module 'bcoin/examples/chain.js' {
  declare module.exports: $Exports<'bcoin/examples/chain'>;
}
declare module 'bcoin/examples/client.js' {
  declare module.exports: $Exports<'bcoin/examples/client'>;
}
declare module 'bcoin/examples/miner.js' {
  declare module.exports: $Exports<'bcoin/examples/miner'>;
}
declare module 'bcoin/examples/node.js' {
  declare module.exports: $Exports<'bcoin/examples/node'>;
}
declare module 'bcoin/examples/peer.js' {
  declare module.exports: $Exports<'bcoin/examples/peer'>;
}
declare module 'bcoin/examples/plugin.js' {
  declare module.exports: $Exports<'bcoin/examples/plugin'>;
}
declare module 'bcoin/examples/tx.js' {
  declare module.exports: $Exports<'bcoin/examples/tx'>;
}
declare module 'bcoin/examples/wallet.js' {
  declare module.exports: $Exports<'bcoin/examples/wallet'>;
}
declare module 'bcoin/lib/bcoin.js' {
  declare module.exports: $Exports<'bcoin/lib/bcoin'>;
}
declare module 'bcoin/lib/bip70/certs.js' {
  declare module.exports: $Exports<'bcoin/lib/bip70/certs'>;
}
declare module 'bcoin/lib/bip70/index.js' {
  declare module.exports: $Exports<'bcoin/lib/bip70/index'>;
}
declare module 'bcoin/lib/bip70/payment.js' {
  declare module.exports: $Exports<'bcoin/lib/bip70/payment'>;
}
declare module 'bcoin/lib/bip70/paymentack.js' {
  declare module.exports: $Exports<'bcoin/lib/bip70/paymentack'>;
}
declare module 'bcoin/lib/bip70/paymentdetails.js' {
  declare module.exports: $Exports<'bcoin/lib/bip70/paymentdetails'>;
}
declare module 'bcoin/lib/bip70/paymentrequest.js' {
  declare module.exports: $Exports<'bcoin/lib/bip70/paymentrequest'>;
}
declare module 'bcoin/lib/bip70/pk.js' {
  declare module.exports: $Exports<'bcoin/lib/bip70/pk'>;
}
declare module 'bcoin/lib/bip70/x509.js' {
  declare module.exports: $Exports<'bcoin/lib/bip70/x509'>;
}
declare module 'bcoin/lib/blockchain/chain.js' {
  declare module.exports: $Exports<'bcoin/lib/blockchain/chain'>;
}
declare module 'bcoin/lib/blockchain/chaindb.js' {
  declare module.exports: $Exports<'bcoin/lib/blockchain/chaindb'>;
}
declare module 'bcoin/lib/blockchain/chainentry.js' {
  declare module.exports: $Exports<'bcoin/lib/blockchain/chainentry'>;
}
declare module 'bcoin/lib/blockchain/common.js' {
  declare module.exports: $Exports<'bcoin/lib/blockchain/common'>;
}
declare module 'bcoin/lib/blockchain/index.js' {
  declare module.exports: $Exports<'bcoin/lib/blockchain/index'>;
}
declare module 'bcoin/lib/blockchain/layout-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/blockchain/layout-browser'>;
}
declare module 'bcoin/lib/blockchain/layout.js' {
  declare module.exports: $Exports<'bcoin/lib/blockchain/layout'>;
}
declare module 'bcoin/lib/btc/amount.js' {
  declare module.exports: $Exports<'bcoin/lib/btc/amount'>;
}
declare module 'bcoin/lib/btc/index.js' {
  declare module.exports: $Exports<'bcoin/lib/btc/index'>;
}
declare module 'bcoin/lib/btc/uri.js' {
  declare module.exports: $Exports<'bcoin/lib/btc/uri'>;
}
declare module 'bcoin/lib/coins/coins.js' {
  declare module.exports: $Exports<'bcoin/lib/coins/coins'>;
}
declare module 'bcoin/lib/coins/coinview.js' {
  declare module.exports: $Exports<'bcoin/lib/coins/coinview'>;
}
declare module 'bcoin/lib/coins/compress.js' {
  declare module.exports: $Exports<'bcoin/lib/coins/compress'>;
}
declare module 'bcoin/lib/coins/index.js' {
  declare module.exports: $Exports<'bcoin/lib/coins/index'>;
}
declare module 'bcoin/lib/coins/undocoins.js' {
  declare module.exports: $Exports<'bcoin/lib/coins/undocoins'>;
}
declare module 'bcoin/lib/crypto/aes.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/aes'>;
}
declare module 'bcoin/lib/crypto/backend-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/backend-browser'>;
}
declare module 'bcoin/lib/crypto/backend.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/backend'>;
}
declare module 'bcoin/lib/crypto/chachapoly.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/chachapoly'>;
}
declare module 'bcoin/lib/crypto/crypto.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/crypto'>;
}
declare module 'bcoin/lib/crypto/ec-elliptic.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/ec-elliptic'>;
}
declare module 'bcoin/lib/crypto/ec-secp256k1.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/ec-secp256k1'>;
}
declare module 'bcoin/lib/crypto/ec.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/ec'>;
}
declare module 'bcoin/lib/crypto/index.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/index'>;
}
declare module 'bcoin/lib/crypto/pk-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/pk-browser'>;
}
declare module 'bcoin/lib/crypto/pk.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/pk'>;
}
declare module 'bcoin/lib/crypto/schnorr.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/schnorr'>;
}
declare module 'bcoin/lib/crypto/scrypt.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/scrypt'>;
}
declare module 'bcoin/lib/crypto/sha256.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/sha256'>;
}
declare module 'bcoin/lib/crypto/siphash.js' {
  declare module.exports: $Exports<'bcoin/lib/crypto/siphash'>;
}
declare module 'bcoin/lib/db/backends-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/db/backends-browser'>;
}
declare module 'bcoin/lib/db/backends.js' {
  declare module.exports: $Exports<'bcoin/lib/db/backends'>;
}
declare module 'bcoin/lib/db/index.js' {
  declare module.exports: $Exports<'bcoin/lib/db/index'>;
}
declare module 'bcoin/lib/db/ldb.js' {
  declare module.exports: $Exports<'bcoin/lib/db/ldb'>;
}
declare module 'bcoin/lib/db/level.js' {
  declare module.exports: $Exports<'bcoin/lib/db/level'>;
}
declare module 'bcoin/lib/db/lowlevelup.js' {
  declare module.exports: $Exports<'bcoin/lib/db/lowlevelup'>;
}
declare module 'bcoin/lib/db/memdb.js' {
  declare module.exports: $Exports<'bcoin/lib/db/memdb'>;
}
declare module 'bcoin/lib/env.js' {
  declare module.exports: $Exports<'bcoin/lib/env'>;
}
declare module 'bcoin/lib/hd/common.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/common'>;
}
declare module 'bcoin/lib/hd/hd.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/hd'>;
}
declare module 'bcoin/lib/hd/index.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/index'>;
}
declare module 'bcoin/lib/hd/mnemonic.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/mnemonic'>;
}
declare module 'bcoin/lib/hd/private.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/private'>;
}
declare module 'bcoin/lib/hd/public.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/public'>;
}
declare module 'bcoin/lib/hd/wordlist-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/wordlist-browser'>;
}
declare module 'bcoin/lib/hd/wordlist.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/wordlist'>;
}
declare module 'bcoin/lib/hd/words/chinese-simplified.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/words/chinese-simplified'>;
}
declare module 'bcoin/lib/hd/words/chinese-traditional.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/words/chinese-traditional'>;
}
declare module 'bcoin/lib/hd/words/english.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/words/english'>;
}
declare module 'bcoin/lib/hd/words/french.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/words/french'>;
}
declare module 'bcoin/lib/hd/words/index.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/words/index'>;
}
declare module 'bcoin/lib/hd/words/italian.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/words/italian'>;
}
declare module 'bcoin/lib/hd/words/japanese.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/words/japanese'>;
}
declare module 'bcoin/lib/hd/words/spanish.js' {
  declare module.exports: $Exports<'bcoin/lib/hd/words/spanish'>;
}
declare module 'bcoin/lib/http/base.js' {
  declare module.exports: $Exports<'bcoin/lib/http/base'>;
}
declare module 'bcoin/lib/http/client.js' {
  declare module.exports: $Exports<'bcoin/lib/http/client'>;
}
declare module 'bcoin/lib/http/index.js' {
  declare module.exports: $Exports<'bcoin/lib/http/index'>;
}
declare module 'bcoin/lib/http/request.js' {
  declare module.exports: $Exports<'bcoin/lib/http/request'>;
}
declare module 'bcoin/lib/http/rpc.js' {
  declare module.exports: $Exports<'bcoin/lib/http/rpc'>;
}
declare module 'bcoin/lib/http/rpcbase.js' {
  declare module.exports: $Exports<'bcoin/lib/http/rpcbase'>;
}
declare module 'bcoin/lib/http/rpcclient.js' {
  declare module.exports: $Exports<'bcoin/lib/http/rpcclient'>;
}
declare module 'bcoin/lib/http/server.js' {
  declare module.exports: $Exports<'bcoin/lib/http/server'>;
}
declare module 'bcoin/lib/http/wallet.js' {
  declare module.exports: $Exports<'bcoin/lib/http/wallet'>;
}
declare module 'bcoin/lib/mempool/fees.js' {
  declare module.exports: $Exports<'bcoin/lib/mempool/fees'>;
}
declare module 'bcoin/lib/mempool/index.js' {
  declare module.exports: $Exports<'bcoin/lib/mempool/index'>;
}
declare module 'bcoin/lib/mempool/layout-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/mempool/layout-browser'>;
}
declare module 'bcoin/lib/mempool/layout.js' {
  declare module.exports: $Exports<'bcoin/lib/mempool/layout'>;
}
declare module 'bcoin/lib/mempool/mempool.js' {
  declare module.exports: $Exports<'bcoin/lib/mempool/mempool'>;
}
declare module 'bcoin/lib/mempool/mempoolentry.js' {
  declare module.exports: $Exports<'bcoin/lib/mempool/mempoolentry'>;
}
declare module 'bcoin/lib/mining/common.js' {
  declare module.exports: $Exports<'bcoin/lib/mining/common'>;
}
declare module 'bcoin/lib/mining/cpuminer.js' {
  declare module.exports: $Exports<'bcoin/lib/mining/cpuminer'>;
}
declare module 'bcoin/lib/mining/index.js' {
  declare module.exports: $Exports<'bcoin/lib/mining/index'>;
}
declare module 'bcoin/lib/mining/mine.js' {
  declare module.exports: $Exports<'bcoin/lib/mining/mine'>;
}
declare module 'bcoin/lib/mining/miner.js' {
  declare module.exports: $Exports<'bcoin/lib/mining/miner'>;
}
declare module 'bcoin/lib/mining/template.js' {
  declare module.exports: $Exports<'bcoin/lib/mining/template'>;
}
declare module 'bcoin/lib/net/bip150.js' {
  declare module.exports: $Exports<'bcoin/lib/net/bip150'>;
}
declare module 'bcoin/lib/net/bip151.js' {
  declare module.exports: $Exports<'bcoin/lib/net/bip151'>;
}
declare module 'bcoin/lib/net/bip152.js' {
  declare module.exports: $Exports<'bcoin/lib/net/bip152'>;
}
declare module 'bcoin/lib/net/common.js' {
  declare module.exports: $Exports<'bcoin/lib/net/common'>;
}
declare module 'bcoin/lib/net/dns-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/net/dns-browser'>;
}
declare module 'bcoin/lib/net/dns.js' {
  declare module.exports: $Exports<'bcoin/lib/net/dns'>;
}
declare module 'bcoin/lib/net/framer.js' {
  declare module.exports: $Exports<'bcoin/lib/net/framer'>;
}
declare module 'bcoin/lib/net/hostlist.js' {
  declare module.exports: $Exports<'bcoin/lib/net/hostlist'>;
}
declare module 'bcoin/lib/net/index.js' {
  declare module.exports: $Exports<'bcoin/lib/net/index'>;
}
declare module 'bcoin/lib/net/packets.js' {
  declare module.exports: $Exports<'bcoin/lib/net/packets'>;
}
declare module 'bcoin/lib/net/parser.js' {
  declare module.exports: $Exports<'bcoin/lib/net/parser'>;
}
declare module 'bcoin/lib/net/peer.js' {
  declare module.exports: $Exports<'bcoin/lib/net/peer'>;
}
declare module 'bcoin/lib/net/pool.js' {
  declare module.exports: $Exports<'bcoin/lib/net/pool'>;
}
declare module 'bcoin/lib/net/proxysocket.js' {
  declare module.exports: $Exports<'bcoin/lib/net/proxysocket'>;
}
declare module 'bcoin/lib/net/seeds/index.js' {
  declare module.exports: $Exports<'bcoin/lib/net/seeds/index'>;
}
declare module 'bcoin/lib/net/seeds/main.js' {
  declare module.exports: $Exports<'bcoin/lib/net/seeds/main'>;
}
declare module 'bcoin/lib/net/seeds/testnet.js' {
  declare module.exports: $Exports<'bcoin/lib/net/seeds/testnet'>;
}
declare module 'bcoin/lib/net/socks.js' {
  declare module.exports: $Exports<'bcoin/lib/net/socks'>;
}
declare module 'bcoin/lib/net/tcp-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/net/tcp-browser'>;
}
declare module 'bcoin/lib/net/tcp.js' {
  declare module.exports: $Exports<'bcoin/lib/net/tcp'>;
}
declare module 'bcoin/lib/net/upnp-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/net/upnp-browser'>;
}
declare module 'bcoin/lib/net/upnp.js' {
  declare module.exports: $Exports<'bcoin/lib/net/upnp'>;
}
declare module 'bcoin/lib/node/config.js' {
  declare module.exports: $Exports<'bcoin/lib/node/config'>;
}
declare module 'bcoin/lib/node/fullnode.js' {
  declare module.exports: $Exports<'bcoin/lib/node/fullnode'>;
}
declare module 'bcoin/lib/node/index.js' {
  declare module.exports: $Exports<'bcoin/lib/node/index'>;
}
declare module 'bcoin/lib/node/logger.js' {
  declare module.exports: $Exports<'bcoin/lib/node/logger'>;
}
declare module 'bcoin/lib/node/node.js' {
  declare module.exports: $Exports<'bcoin/lib/node/node'>;
}
declare module 'bcoin/lib/node/nodeclient.js' {
  declare module.exports: $Exports<'bcoin/lib/node/nodeclient'>;
}
declare module 'bcoin/lib/node/spvnode.js' {
  declare module.exports: $Exports<'bcoin/lib/node/spvnode'>;
}
declare module 'bcoin/lib/pkg.js' {
  declare module.exports: $Exports<'bcoin/lib/pkg'>;
}
declare module 'bcoin/lib/primitives/abstractblock.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/abstractblock'>;
}
declare module 'bcoin/lib/primitives/address.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/address'>;
}
declare module 'bcoin/lib/primitives/block.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/block'>;
}
declare module 'bcoin/lib/primitives/coin.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/coin'>;
}
declare module 'bcoin/lib/primitives/headers.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/headers'>;
}
declare module 'bcoin/lib/primitives/index.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/index'>;
}
declare module 'bcoin/lib/primitives/input.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/input'>;
}
declare module 'bcoin/lib/primitives/invitem.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/invitem'>;
}
declare module 'bcoin/lib/primitives/keyring.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/keyring'>;
}
declare module 'bcoin/lib/primitives/memblock.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/memblock'>;
}
declare module 'bcoin/lib/primitives/merkleblock.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/merkleblock'>;
}
declare module 'bcoin/lib/primitives/mtx.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/mtx'>;
}
declare module 'bcoin/lib/primitives/netaddress.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/netaddress'>;
}
declare module 'bcoin/lib/primitives/outpoint.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/outpoint'>;
}
declare module 'bcoin/lib/primitives/output.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/output'>;
}
declare module 'bcoin/lib/primitives/tx.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/tx'>;
}
declare module 'bcoin/lib/primitives/txmeta.js' {
  declare module.exports: $Exports<'bcoin/lib/primitives/txmeta'>;
}
declare module 'bcoin/lib/protocol/consensus.js' {
  declare module.exports: $Exports<'bcoin/lib/protocol/consensus'>;
}
declare module 'bcoin/lib/protocol/errors.js' {
  declare module.exports: $Exports<'bcoin/lib/protocol/errors'>;
}
declare module 'bcoin/lib/protocol/index.js' {
  declare module.exports: $Exports<'bcoin/lib/protocol/index'>;
}
declare module 'bcoin/lib/protocol/network.js' {
  declare module.exports: $Exports<'bcoin/lib/protocol/network'>;
}
declare module 'bcoin/lib/protocol/networks.js' {
  declare module.exports: $Exports<'bcoin/lib/protocol/networks'>;
}
declare module 'bcoin/lib/protocol/policy.js' {
  declare module.exports: $Exports<'bcoin/lib/protocol/policy'>;
}
declare module 'bcoin/lib/protocol/timedata.js' {
  declare module.exports: $Exports<'bcoin/lib/protocol/timedata'>;
}
declare module 'bcoin/lib/script/common.js' {
  declare module.exports: $Exports<'bcoin/lib/script/common'>;
}
declare module 'bcoin/lib/script/index.js' {
  declare module.exports: $Exports<'bcoin/lib/script/index'>;
}
declare module 'bcoin/lib/script/opcode.js' {
  declare module.exports: $Exports<'bcoin/lib/script/opcode'>;
}
declare module 'bcoin/lib/script/program.js' {
  declare module.exports: $Exports<'bcoin/lib/script/program'>;
}
declare module 'bcoin/lib/script/script.js' {
  declare module.exports: $Exports<'bcoin/lib/script/script'>;
}
declare module 'bcoin/lib/script/scriptnum.js' {
  declare module.exports: $Exports<'bcoin/lib/script/scriptnum'>;
}
declare module 'bcoin/lib/script/sigcache.js' {
  declare module.exports: $Exports<'bcoin/lib/script/sigcache'>;
}
declare module 'bcoin/lib/script/stack.js' {
  declare module.exports: $Exports<'bcoin/lib/script/stack'>;
}
declare module 'bcoin/lib/script/witness.js' {
  declare module.exports: $Exports<'bcoin/lib/script/witness'>;
}
declare module 'bcoin/lib/types.js' {
  declare module.exports: $Exports<'bcoin/lib/types'>;
}
declare module 'bcoin/lib/utils/asn1.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/asn1'>;
}
declare module 'bcoin/lib/utils/asyncemitter.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/asyncemitter'>;
}
declare module 'bcoin/lib/utils/asyncobject.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/asyncobject'>;
}
declare module 'bcoin/lib/utils/base32.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/base32'>;
}
declare module 'bcoin/lib/utils/base58.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/base58'>;
}
declare module 'bcoin/lib/utils/bloom.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/bloom'>;
}
declare module 'bcoin/lib/utils/co.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/co'>;
}
declare module 'bcoin/lib/utils/encoding.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/encoding'>;
}
declare module 'bcoin/lib/utils/fs.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/fs'>;
}
declare module 'bcoin/lib/utils/heap.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/heap'>;
}
declare module 'bcoin/lib/utils/index.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/index'>;
}
declare module 'bcoin/lib/utils/ip.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/ip'>;
}
declare module 'bcoin/lib/utils/lazy-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/lazy-browser'>;
}
declare module 'bcoin/lib/utils/lazy.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/lazy'>;
}
declare module 'bcoin/lib/utils/list.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/list'>;
}
declare module 'bcoin/lib/utils/lock.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/lock'>;
}
declare module 'bcoin/lib/utils/lru.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/lru'>;
}
declare module 'bcoin/lib/utils/map.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/map'>;
}
declare module 'bcoin/lib/utils/murmur3.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/murmur3'>;
}
declare module 'bcoin/lib/utils/native.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/native'>;
}
declare module 'bcoin/lib/utils/nexttick-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/nexttick-browser'>;
}
declare module 'bcoin/lib/utils/nexttick.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/nexttick'>;
}
declare module 'bcoin/lib/utils/nfkd-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/nfkd-browser'>;
}
declare module 'bcoin/lib/utils/nfkd.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/nfkd'>;
}
declare module 'bcoin/lib/utils/pem.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/pem'>;
}
declare module 'bcoin/lib/utils/protobuf.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/protobuf'>;
}
declare module 'bcoin/lib/utils/rbt.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/rbt'>;
}
declare module 'bcoin/lib/utils/reader.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/reader'>;
}
declare module 'bcoin/lib/utils/staticwriter.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/staticwriter'>;
}
declare module 'bcoin/lib/utils/util.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/util'>;
}
declare module 'bcoin/lib/utils/validator.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/validator'>;
}
declare module 'bcoin/lib/utils/writer.js' {
  declare module.exports: $Exports<'bcoin/lib/utils/writer'>;
}
declare module 'bcoin/lib/wallet/account.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/account'>;
}
declare module 'bcoin/lib/wallet/client.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/client'>;
}
declare module 'bcoin/lib/wallet/common.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/common'>;
}
declare module 'bcoin/lib/wallet/http.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/http'>;
}
declare module 'bcoin/lib/wallet/index.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/index'>;
}
declare module 'bcoin/lib/wallet/layout-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/layout-browser'>;
}
declare module 'bcoin/lib/wallet/layout.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/layout'>;
}
declare module 'bcoin/lib/wallet/masterkey.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/masterkey'>;
}
declare module 'bcoin/lib/wallet/path.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/path'>;
}
declare module 'bcoin/lib/wallet/plugin.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/plugin'>;
}
declare module 'bcoin/lib/wallet/records.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/records'>;
}
declare module 'bcoin/lib/wallet/rpc.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/rpc'>;
}
declare module 'bcoin/lib/wallet/server.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/server'>;
}
declare module 'bcoin/lib/wallet/txdb.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/txdb'>;
}
declare module 'bcoin/lib/wallet/wallet.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/wallet'>;
}
declare module 'bcoin/lib/wallet/walletdb.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/walletdb'>;
}
declare module 'bcoin/lib/wallet/walletkey.js' {
  declare module.exports: $Exports<'bcoin/lib/wallet/walletkey'>;
}
declare module 'bcoin/lib/workers/framer.js' {
  declare module.exports: $Exports<'bcoin/lib/workers/framer'>;
}
declare module 'bcoin/lib/workers/index.js' {
  declare module.exports: $Exports<'bcoin/lib/workers/index'>;
}
declare module 'bcoin/lib/workers/jobs.js' {
  declare module.exports: $Exports<'bcoin/lib/workers/jobs'>;
}
declare module 'bcoin/lib/workers/master.js' {
  declare module.exports: $Exports<'bcoin/lib/workers/master'>;
}
declare module 'bcoin/lib/workers/packets.js' {
  declare module.exports: $Exports<'bcoin/lib/workers/packets'>;
}
declare module 'bcoin/lib/workers/parser-client.js' {
  declare module.exports: $Exports<'bcoin/lib/workers/parser-client'>;
}
declare module 'bcoin/lib/workers/parser.js' {
  declare module.exports: $Exports<'bcoin/lib/workers/parser'>;
}
declare module 'bcoin/lib/workers/worker-browser.js' {
  declare module.exports: $Exports<'bcoin/lib/workers/worker-browser'>;
}
declare module 'bcoin/lib/workers/worker.js' {
  declare module.exports: $Exports<'bcoin/lib/workers/worker'>;
}
declare module 'bcoin/lib/workers/workerpool.js' {
  declare module.exports: $Exports<'bcoin/lib/workers/workerpool'>;
}
declare module 'bcoin/migrate/chaindb0to1.js' {
  declare module.exports: $Exports<'bcoin/migrate/chaindb0to1'>;
}
declare module 'bcoin/migrate/chaindb1to2.js' {
  declare module.exports: $Exports<'bcoin/migrate/chaindb1to2'>;
}
declare module 'bcoin/migrate/coins-old.js' {
  declare module.exports: $Exports<'bcoin/migrate/coins-old'>;
}
declare module 'bcoin/migrate/coinview-old.js' {
  declare module.exports: $Exports<'bcoin/migrate/coinview-old'>;
}
declare module 'bcoin/migrate/compress-old.js' {
  declare module.exports: $Exports<'bcoin/migrate/compress-old'>;
}
declare module 'bcoin/migrate/ensure-tip-index.js' {
  declare module.exports: $Exports<'bcoin/migrate/ensure-tip-index'>;
}
declare module 'bcoin/migrate/walletdb2to3.js' {
  declare module.exports: $Exports<'bcoin/migrate/walletdb2to3'>;
}
declare module 'bcoin/migrate/walletdb3to4.js' {
  declare module.exports: $Exports<'bcoin/migrate/walletdb3to4'>;
}
declare module 'bcoin/migrate/walletdb4to5.js' {
  declare module.exports: $Exports<'bcoin/migrate/walletdb4to5'>;
}
declare module 'bcoin/migrate/walletdb5to6.js' {
  declare module.exports: $Exports<'bcoin/migrate/walletdb5to6'>;
}
declare module 'bcoin/scripts/dump.js' {
  declare module.exports: $Exports<'bcoin/scripts/dump'>;
}
declare module 'bcoin/scripts/fuzz.js' {
  declare module.exports: $Exports<'bcoin/scripts/fuzz'>;
}
declare module 'bcoin/scripts/gen.js' {
  declare module.exports: $Exports<'bcoin/scripts/gen'>;
}
declare module 'bcoin/vendor/setimmediate.js' {
  declare module.exports: $Exports<'bcoin/vendor/setimmediate'>;
}
declare module 'bcoin/vendor/unorm.js' {
  declare module.exports: $Exports<'bcoin/vendor/unorm'>;
}
