// flow-typed signature: 2849579ad8dda7785593fce35e7021fd
// flow-typed version: <<STUB>>/graph-theory-ford-fulkerson_v^1.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graph-theory-ford-fulkerson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graph-theory-ford-fulkerson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graph-theory-ford-fulkerson/example/example' {
  declare module.exports: any;
}

declare module 'graph-theory-ford-fulkerson/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graph-theory-ford-fulkerson/example/example.js' {
  declare module.exports: $Exports<'graph-theory-ford-fulkerson/example/example'>;
}
declare module 'graph-theory-ford-fulkerson/index' {
  declare module.exports: $Exports<'graph-theory-ford-fulkerson'>;
}
declare module 'graph-theory-ford-fulkerson/index.js' {
  declare module.exports: $Exports<'graph-theory-ford-fulkerson'>;
}
declare module 'graph-theory-ford-fulkerson/test/index.js' {
  declare module.exports: $Exports<'graph-theory-ford-fulkerson/test/index'>;
}
