// flow-typed signature: 49b561be32534814522dc2da04fa8dea
// flow-typed version: <<STUB>>/sorted-set_v1.x.x/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sorted-set'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sorted-set' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sorted-set/examples/distance' {
  declare module.exports: any;
}

declare module 'sorted-set/examples/kademlia' {
  declare module.exports: any;
}

declare module 'sorted-set/examples/ttl' {
  declare module.exports: any;
}

declare module 'sorted-set/lib/intersect-sorted' {
  declare module.exports: any;
}

declare module 'sorted-set/lib/intersect-unique' {
  declare module.exports: any;
}

declare module 'sorted-set/lib/set' {
  declare module.exports: any;
}

declare module 'sorted-set/test/index' {
  declare module.exports: any;
}

declare module 'sorted-set/test/set' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sorted-set/examples/distance.js' {
  declare module.exports: $Exports<'sorted-set/examples/distance'>;
}
declare module 'sorted-set/examples/kademlia.js' {
  declare module.exports: $Exports<'sorted-set/examples/kademlia'>;
}
declare module 'sorted-set/examples/ttl.js' {
  declare module.exports: $Exports<'sorted-set/examples/ttl'>;
}
declare module 'sorted-set/index' {
  declare module.exports: $Exports<'sorted-set'>;
}
declare module 'sorted-set/index.js' {
  declare module.exports: $Exports<'sorted-set'>;
}
declare module 'sorted-set/lib/intersect-sorted.js' {
  declare module.exports: $Exports<'sorted-set/lib/intersect-sorted'>;
}
declare module 'sorted-set/lib/intersect-unique.js' {
  declare module.exports: $Exports<'sorted-set/lib/intersect-unique'>;
}
declare module 'sorted-set/lib/set.js' {
  declare module.exports: $Exports<'sorted-set/lib/set'>;
}
declare module 'sorted-set/test/index.js' {
  declare module.exports: $Exports<'sorted-set/test/index'>;
}
declare module 'sorted-set/test/set.js' {
  declare module.exports: $Exports<'sorted-set/test/set'>;
}
